name: Cowsay
on: push

jobs:
    Ascii_job:
        runs-on: ubuntu-latest
        steps:
              - name: install cowsay program
                run: D:\Bank Misr DevOps Internship\github-actions-tolearn\script.sh