name: Cowsay
on: push

jobs:
    Ascii_job:
        runs-on: self-hosted
        steps:
              - name: Checkout repository
                uses: actions/checkout@v5
              - name: install cowsay program
                run: |
                  D:\Bank Misr DevOps Internship\github-actions-tolearn\script.sh