name: Cowsay
on: push

jobs:
    Ascii_job:
        runs-on: ubuntu-latest
        steps:
              - name: Checkout repository
                uses: actions/checkout@v5

              - name: install cowsay program
                run: |
                  bash script.sh