name: my first workflow | shell script
on: 
    push:
        branches:
        - main
jobs:
    omar_job:
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run: echo "Hello Omar, this is my first workflow"

    job2:
        needs: omar_job
        runs-on: ubuntu-latest
        steps:
            - name: list files2
              run: echo "Hello Omar, this is my second workflow"
           
            